### PR TITLE
Hey this is it | New bear model and texture, shapeshifting and other improvements

### PR DESCRIPTION
**Pull request by Arsakes**

### CODE REVIEW

**Comment by Arsakes** [comment]
So yea, merging by rebase would be ideal, maybe there would an option to rebase after conflict resolution.

**Comment by Swyter** [comment]
Hi, @Arsakes. Ideally you'd be the one rebasing the changes on top of `origin/master`. I can do it for you, I think. But poor @In-Vain probably doesn't want to deal with it. I appreciate you letting us commit on your `master` branch.

I'll try to fix it.

**Comment by Swyter** [comment]
@In-Vain It should be good to go. Easy peasy. Haven't reviewed the commits themselves, though.

**Comment by Arsakes** [comment]
Yes, I would love to make rebase on top of your master, to simplify your merges.
We did normal merge first time and repo history on my side got fucked a bit.

**Pull request merged**
