### PR TITLE
Correct a typo when displaying extra EXP gained from INT

### PR DESCRIPTION
**Pull request by Noxbru**

### CODE REVIEW

**Comment by Swyter** [comment]
Looks good to me, keep in mind that we usually commit the generated `.txt` files for both M&B 1.011 and Warband in the same revision to keep things tidy and to ensure it works.

Not a big issue, makes it easier to revert and test.

**Comment by Noxbru** [comment]
Okay. Which files would I need to add to the commit? or just a `git add -u` after doing the `build_module{,_wb}.sh` will suffice?

**Comment by Swyter** [comment]
Yeah, exactly. I think we can still merge it like this, so it's not a big issue. Just let me know.

I don't want to be annoying. ¯\\\_(ツ)_/¯

**Comment by Noxbru** [comment]
No worries, I can add another commit with the relevant changes. It is just that I think that if a user is knowledgeable enough to come here for the latest version, they should also be for running a couple of scripts, but that is just me.

**Comment by Swyter** [comment]
Darn, you've changed all the line ends to UNIX in all the files.

You need to install the `flip` utility or change it to something like `dos2unix`.

https://github.com/tldmod/tldmod/blob/master/ModuleSystem/build_module.sh#L55

**Comment by Swyter** [comment]
It's fine, it's a small typo. Now that you've reverted it I shouldn't be this picky. ¯\\\_(ツ)_/¯

**Pull request merged**
