### PR TITLE
Add some missed strings to language base files

### PR DESCRIPTION
**Pull request by Fantu**
I created the template from warband with TLD build on rev 2177, major of
strings different don't seems needed to be added (empty, with only
variables, cheat, debug ecc...).
I don't know automatic way to exclude these, so I manually do a fast
comparison and added these strings that seems really needed.

### CODE REVIEW

**Comment by Swyter** [comment]
@Fantu That's what I originally did to exclude all the useless strings that don't need to be translated. Still, there are some new strings I'm not happy with, and I want to avoid their inclusion until they meet the standards.

**Comment by Fantu** [comment]
@Swyter You are free to add another commit that remove the strings you don't want add before accept the PR, or you can also did another template update complete and better.
After I saw many untranslatable strings with a short TLD play with a language fully translated I only tried to add some missed strings in a short time.

**Comment by Swyter** [comment]
@Fantu I prefer doing it on my own and remove as many duplicated references as possible in one commit before updating the base language template, instead of going back and forth. I don't want to make mistakes.

**Comment by Fantu** [comment]
@Swyter ok, thanks

**Pull request closed without merging**
