### PR TITLE
uninitialized variable leads to problem with troops tree

### PR DESCRIPTION
**Pull request by Ruslan-700**

### CODE REVIEW

**Comment by Swyter** [comment]
Oh, K700 himself!

Hi, mate. Good catch. I guess this caused side effects in WSE2, did it crash when subtracting a garbage value? Or do you have a way to flag registers as uninitialized and this was logged on access while diagnosing something else? Is the behavior different between both engines?

Thanks for the pull request, I wonder if having some kind of static analyzer pass that goes backwards from operations that access variable contents while compiling module system functions and reports these subtle bugs would be worthwhile. ¯\\\_(ツ)_/¯

**Comment by Swyter** [comment]
I see that the code that uses it checks for the `0, ":num_factions"` range while looping, so using `-1` should be fine, I think.

**Comment by Ruslan-700** [comment]
Hello. In this example in the Warband engine, the uninitialized variable for the farmer returned 3, which was likely the previous value of this local variable. In WSE2, the default behavior is now to reset all local variables to 0, because scripters expect to see 0 there and this helped with most of these errors, but not in this case. I don't think copying such unpredictable behavior for compatibility is a good idea.

**Comment by Swyter** [comment]
I see, makes sense. Yeah, seems like a saner default, even if forces people to track down a few edge cases.

--

Thanks for making TLD work well. By the way, seems like there's a remaining WSE2 compatibility issue with TLD trolls. This is what players reported on our Discord server:

(https://discord.com/channels/492783428635328532/492783429872517121/1194375139597488148)

> *Btw, it turns out WSE2 got updated to make this mod compatible... mostly. No more crashes, but the trolls run at horse speed*

**Comment by Ruslan-700** [comment]
Trolls have been fixed and will be in the next update.

**Comment by Swyter** [comment]
Great, what was the issue? Agent scaling messing with the speed? Was it difficult to track down? I'm sure the players appreciate how fast you are fixing these. 🐧

**Comment by Ruslan-700** [comment]
Agents' maximum walking speed is now limited. One of the changes in the latest Warband updates that was not discovered before.
https://github.com/tldmod/tldmod/assets/22572215/a4cf43d7-8255-4397-995d-ba512951f36a

**Pull request merged**
